import { Selector } from 'testcafe';
class NBLoc {
    constructor(){
    this.lobbutton=Selector('[id="NewSubmission:NewSubmissionScreen:ProductOffersDV:ProductSelectionLV:6:addSubmission"]')
    this.offerbutton=Selector('[id="SubmissionWizard:OfferingScreen:OfferingSelection-inputEl"]')
    this.nextbutton=Selector('[id="SubmissionWizard:Next-btnInnerEl"]')
    this.effectivedate=Selector('[id="SubmissionWizard:LOBWizardStepGroup:SubmissionWizard_PolicyInfoScreen:SubmissionWizard_PolicyInfoDV:DateQuoteNeeded-inputEl"]')
    this.term=Selector('[id="SubmissionWizard:LOBWizardStepGroup:SubmissionWizard_PolicyInfoScreen:SubmissionWizard_PolicyInfoDV:PolicyInfoInputSet:TermType-inputEl"]')
    this.adddriverbutton=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PADriversScreen:PADriversPanelSet:DriversListDetailPanel:DriversLV_tb:AddDriver-btnInnerEl"]')
    this.newdriverbutton=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PADriversScreen:PADriversPanelSet:DriversListDetailPanel:DriversLV_tb:AddDriver:0:ContactType-textEl"]')
    this.selectnoofaccident=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:PolicyDriverInfoDV:numberofaccidents-inputEl"]')
    this.selectnoofviolation=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:PolicyDriverInfoDV:numberofviolations-inputEl"]')
    this.licensedyear=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:PolicyDriverInfoDV:yearlicensed-inputEl"]')
    this.firstnamedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:PolicyContactRoleNameInputSet:GlobalPersonNameInputSet:FirstName-inputEl"]')
    this.lastnamedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:PolicyContactRoleNameInputSet:GlobalPersonNameInputSet:LastName-inputEl"]')
    this.dateofbirthdriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:PolicyContactRoleNameInputSet:DateOfBirth-inputEl"]')
    this.Address1driverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:AddressInputSet:globalAddressContainer:GlobalAddressInputSet:AddressLine1-inputEl"]')
    this.citydriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:AddressInputSet:globalAddressContainer:GlobalAddressInputSet:City-inputEl"]')
    this.statedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:AddressInputSet:globalAddressContainer:GlobalAddressInputSet:State-inputEl"]')
    this.zipcodedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:AddressInputSet:globalAddressContainer:GlobalAddressInputSet:PostalCode-inputEl"]') 
    this.addresstypedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:AddressType-inputEl"]') 
    this.licensenumberdriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:LicenseInputSet:LicenseNumber-inputEl"]')
    this.licensestatedriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:NewPolicyContactRoleDetailsCV:PolicyContactDetailsDV:LicenseInputSet:LicenseState-inputEl"]')
    this.okbuttondriverpage=Selector('[id="NewPolicyDriverPopup:ContactDetailScreen:Update-btnInnerEl"]')
    this.nextbuttondriverpage=Selector('[id="SubmissionWizard:Next-btnInnerEl"]')
    this.vehiclebutton=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel_tb:Add-btnInnerEl"]')
    this.vehiclenumber=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel:VehiclesDetailsCV:PersonalAuto_VehicleDV:Vin_DV-inputEl"]')
    this.costnewbutton=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel:VehiclesDetailsCV:PersonalAuto_VehicleDV:CostNew_DV-inputEl"]')
    this.licensestatevehiclepage=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel:VehiclesDetailsCV:PersonalAuto_VehicleDV:LicenseState_DV-inputEl"]')
    this.adddriverbuttonvehiclepage=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel:VehiclesDetailsCV:PersonalAuto_AssignDriversDV:DriverPctLV_tb:AddDriver-btnInnerEl"]')
    this.driverselection=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PAVehiclesScreen:PAVehiclesPanelSet:VehiclesListDetailPanel:VehiclesDetailsCV:PersonalAuto_AssignDriversDV:DriverPctLV_tb:AddDriver:0:Driver-textEl"]')
    this.coveragebutton=Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PersonalAutoScreen:PersonalAuto_AllVehicleCoveragesDV:PALiabCategoryIterator:1:CoverageInputSet:CovPatternInputGroup:_checkbox"]')
    this.quotebutton=Selector('[id="SubmissionWizard:SubmissionWizard_PolicyReviewScreen:JobWizardToolbarButtonSet:QuoteOrReview-btnInnerEl"]')
    this.bindbutton=Selector('[id="SubmissionWizard:SubmissionWizard_QuoteScreen:JobWizardToolbarButtonSet:BindOptions-btnInnerEl"]')
    this.issuebutton=Selector('[id="SubmissionWizard:SubmissionWizard_QuoteScreen:JobWizardToolbarButtonSet:BindOptions:BindAndIssue-textEl"]')
    this.validationresult=Selector('[id="wsTabBar:wsTab_0-btnInnerEl"]')
    this.detailsbutton=Selector('[id="UWBlockProgressIssuesPopup:IssuesScreen:DetailsButton-btnInnerEl"]')
    this.issueokbutton=Selector('[id="button-1005-btnInnerEl"]')
    this.policyreviewelement=Selector('[id="SubmissionWizard:SubmissionWizard_PolicyReviewScreen:ttlBar"]')
    this.riskanalysiselemt=Selector('[id="SubmissionWizard:Job_RiskAnalysisScreen:0"]')
    this.getpolicynum=Selector('[id="PolicyFile:PolicyFileMenuInfoBar:PolicyNumber-btnInnerEl"]')
    this.policynumclick=Selector('[id="JobComplete:JobWizardInfoBar:PolicyNumber-btnInnerEl"]')
    this.medicallimitcheck= Selector('[id="SubmissionWizard:LOBWizardStepGroup:LineWizardStepSet:PersonalAutoScreen:PersonalAuto_AllVehicleCoveragesDV:PALiabCategoryIterator:1:CoverageInputSet:CovPatternInputGroup:_checkbox"]')
    this.getpolicynumber= Selector('[id="PolicyFile_Summary:Policy_SummaryScreen:Policy_Summary_PolicyDV:PolicyNumber-inputEl"]')
    
    }
}
export default new NBLoc(); 